### ISSUE TITLE
Create an AppImage from an external Debian package 

### ISSUE THREAD

**Issue by UriHerrera** [simoniz0r/deb2appimage#10]
First, thanks for creating this tool.

From what I understand how this tool works, it gets the dependencies and the software that's packaged in the AppImage from the distribution repositories, it's straightforward however I'm a little confused as to how I can create an AppImage of software that is not in the distribution repositories.

For example, I want to create an AppImage of this software: https://github.com/mauikit/index

There's a deb package here:
- http://repo.nxos.org/development/pool/main/i/index/index_0%2Bgit20190425-1_amd64.deb

And its dependencies are these:

- http://repo.nxos.org/development/pool/main/m/mauikit/libmauikit_0%2Bgit20190421-1_amd64.deb

- http://repo.nxos.org/development/pool/main/m/mauikit/qml-module-org-kde-mauikit_0%2Bgit20190421-1_amd64.deb

- http://repo.nxos.org/development/pool/main/m/mauikit/mauikit-dev_0%2Bgit20190421-1_amd64.deb

- http://repo.nxos.org/development/pool/main/q/qml-module-qmltermwidget/qml-module-qmltermwidget_1.0.1-1_amd64.deb

The main problem as I mention is that I'm not sure how to add these external dependencies to the JSON configuration file.

**Comment by simoniz0r** [comment]
Download them using `curl` to `~/.cache/deb2appimage/debs/` as shown [here](https://github.com/simoniz0r/deb2appimage#buildinfo).
