### ISSUE TITLE
App with more then one executable

### ISSUE THREAD

**Issue by igorguida** [simoniz0r/deb2appimage#5]
My problem is that the app I'm trying to convert as appimage has many different executable, so It's not clear how to write the json file, for example, this is my situation:

{
    "buildinfo": [
    {
        "prerun": [
            "curl -sL  https://launchpad.net/~me/+archive/ubuntu/artful/+files/package_amd64.deb -o ~/.cache/deb2appimage/debs/package_amd64.deb"
        ],
        "name": "app1",
        "name": "app2",
        "name": "app3",
        "name": "app4",
        "name": "app5",
        "name": "app17",
        "version": "linux",
        "deps": " libqt4-sql-sqlite, libavahi-client3, libavahi-common3, libavahi-compat-libdnssd1, libc6, libgcc1, libgl1-mesa-glx, libgl1, libqt4-dbus, libqt4-help, libqt4-network, libqt4-opengl, libqt4-svg, libqt4-xml, libqtcore4, libqtgui4, libqtwebkit4, libqwt5-qt4, libsdl2-2.0-0, libstdc++6, libudev1, libxml2",
        "repoarch": "amd64",
        "distrorepo": "Debian",
        "repoversion": "sid",
        "binarypath": "/usr/bin/app1",
        "binarypath": "/usr/bin/app2",
        "binarypath": "/usr/bin/app3",
        "binarypath": "/usr/bin/app18",
        "binarypath": "/usr/bin/app19",
        "desktoppath": "/usr/share/applications/app1.desktop",
        "desktoppath": "/usr/share/applications/app2.desktop",
        "desktoppath": "/usr/share/applications/app3.desktop",
        "desktoppath": "/usr/share/applications/app4.desktop",
        "desktoppath": "/usr/share/applicationsapp9.desktop",
        "iconpath": "/usr/share/icons/hicolor/48x48/apps/app1.png",
        "iconpath": "/usr/share/icons/hicolor/48x48/apps/app2.png",
        "iconpath": "/usr/share/icons/hicolor/48x48/apps/app3.png",
        "iconpath": "/usr/share/icons/hicolor/48x48/apps/app4.png",
        "iconpath": "/usr/share/icons/hicolor/48x48/apps/app9.png",
        "usewrapper": "false",
        "postrun": [
            null
        ]
    }
    ],
    "apprunconf": [
    {
        "setpath": "true",
        "setlibpath": "true",
        "setpythonpath": "false",
        "setpythonhome": "false",
        "setpythondontwritebytecode": "false",
        "setxdgdatadirs": "true",
        "setperllib": "false",
        "setgsettingsschemadir": "false",
        "setqtpluginpath": "true",
        "exec": "/usr/bin/app1"
        "exec": "/usr/bin/app2"
    }
    ],
    "authors": [
    {
        "type": "Author",
        "author": "Test",
        "url": "https://test.com"
    },
    {
        "type": "AppImage Maintainer",
        "author": "test",
        "url": "https://test.it"
    }
    ]
}

So my problem is that I have many diffferent binary and only some of them have a .desktop files so I can't uderstand how to put things working togheter. They are all one project that use exactly the same library and that I compile like one project. So, is there a way to have deb2appimage working with a deb package with many ececutables in it or no?
Thank you

**Comment by simoniz0r** [comment]
This is kind of a limitation of AppImage (and other containers also AFAIK).  The only way I really know of to handle this would be to write a script that would detect the user input and run the relevant command inside of the AppImage and use that as the target binary.
