### ISSUE TITLE
[Feature Request] Extract Info From Local deb

### ISSUE THREAD

**Issue by zero77** [simoniz0r/deb2appimage#9]
Can you please provide an argument to extract all info from a local deb, instead of using a json.
Thanks

**Comment by simoniz0r** [comment]
This probably won't happen as there can be dependencies that we don't want to include in an AppImage, and it would require me to parse the dependencies against a list of blacklisted packages.

**Comment by zero77** [comment]
@simoniz0r 
Would it be possible if there was an include/exclude option for dependencies, where the user has to select the dependencies they want.
